[package]
name = "rs_mate_poe"
version = "1.5.0"
authors = ["Blobfolio, LLC. <hello@blobfolio.com>"]
edition = "2021"
rust-version = "1.62"
description = "WASM port of Screen Mate Poe."
license = "WTFPL"
repository = "https://github.com/Blobfolio/js-mate-poe"
readme = "README.md"
publish = false

[package.metadata.bashman]
name = "RS Mate Poe"
bash-dir = "./"
man-dir = "./"
credits-dir = "./"

[lib]
crate-type = ["cdylib"]

[build-dependencies]
guff_css = "0.1.*"
imagesize = "0.12.*"

[dependencies]
wasm-bindgen = "=0.2.85"

[dependencies.gloo-console]
version = "0.2.*"
optional = true

[dependencies.web-sys]
version = "=0.3.62"
features = [
	"AddEventListenerOptions",
	"Document",
	"Element",
	"Event",
	"EventTarget",
	"HtmlElement",
	"MouseEvent",
	"ShadowRoot",
	"ShadowRootInit",
	"ShadowRootMode",
	"Window",
]

[features]
default = []

# The Firefox browser extension handles audio differently, and has no dblclick
# event listener. Note: do not enable this in conjunction with other features!
firefox = ["web-sys/Node"]

# The director mode exposes additional browserland methods to make it easier to
# preview and debug animations, like Poe.list, Poe.play, and Poe.speed.
director = ["gloo-console"]

[profile.release]
lto = true
codegen-units = 1
strip = true
