module.exports = {
	multipass: true,
	plugins: [
		'cleanupAttrs',
		'cleanupEnableBackground',
		'cleanupListOfValues',
		'cleanupNumericValues',
		'collapseGroups',
		'convertColors',
		'convertPathData',
		'convertShapeToPath',
		'convertStyleToAttrs',
		'convertTransform',
		'inlineStyles',
		'mergePaths',
		'minifyStyles',
		'moveElemsAttrsToGroup',
		'removeComments',
		'removeDesc',
		'removeDoctype',
		'removeEditorsNSData',
		'removeEmptyAttrs',
		'removeEmptyContainers',
		'removeEmptyText',
		'removeHiddenElems',
		'removeMetadata',
		'removeNonInheritableGroupAttrs',
		'removeOffCanvasPaths',
		'removeScriptElement',
		'removeStyleElement',
		'removeUnknownsAndDefaults',
		'removeUnusedNS',
		'removeUselessDefs',
		'removeUselessStrokeAndFill',
		'removeXMLProcInst',
		'reusePaths',
		{
			name: 'removeAttrs',
			params: {
				attrs: '(aria-label|font-face|font-family|font-size|font-style|font-variant|font-weight|letter-spacing|line-height|text-align|word-spacing)'
			},
		},
		{
			name: 'sortAttrs',
			params: {
				xmlnsOrder: 'alphabetical',
			},
		},
	],
};
