name: Build

on:
  push:
    branches: []
  pull_request:
    branches: []

defaults:
  run:
    shell: bash

env:
  CARGO_TERM_COLOR: always

jobs:
  all:
    name: All

    strategy:
      matrix:
        target: [ x86_64-unknown-linux-gnu ]

    runs-on: ubuntu-latest

    env:
      RUSTFLAGS: "-D warnings"
      CARGO_BUILD_TARGET: "wasm32-unknown-unknown"
      CARGO_TARGET_WASM32_UNKNOWN_UNKNOWN_RUNNER: "wasm-bindgen-test-runner"

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        targets: wasm32-unknown-unknown
        components: clippy

    - name: Info
      run: |
        rustup --version
        cargo --version
        rustup target add --toolchain stable x86_64-unknown-linux-gnu
        cargo clippy --version
        cargo install wasm-bindgen-cli --locked --target x86_64-unknown-linux-gnu
        rustup target remove --toolchain stable x86_64-unknown-linux-gnu

    - name: Build (Debug)
      run: |
        cargo build --no-default-features
        cargo build --no-default-features --features director
        cargo build --no-default-features --features firefox

    - name: Build (Release)
      run: |
        cargo build --release --no-default-features
        cargo build --release --no-default-features --features director
        cargo build --release --no-default-features --features firefox

    - name: Clippy
      run: |
        cargo clippy --release --no-default-features
        cargo clippy --release --no-default-features --features director
        cargo clippy --release --no-default-features --features firefox

    - name: Tests (Debug)
      run: |
        cargo test --no-default-features
        cargo test --no-default-features --features director
        cargo test --no-default-features --features firefox

    - name: Tests (Release)
      run: |
        cargo test --release --no-default-features
        cargo test --release --no-default-features --features director
        cargo test --release --no-default-features --features firefox
