name: MSRV

on:
  push:
    branches: []
  pull_request:
    branches: []

defaults:
  run:
    shell: bash

env:
  CARGO_TERM_COLOR: always

jobs:
  all:
    name: All

    strategy:
      matrix:
        target: [ x86_64-unknown-linux-gnu ]

    runs-on: ubuntu-latest

    env:
      RUSTFLAGS: "-D warnings"

    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}
    - uses: taiki-e/install-action@v2
      with:
        tool: cargo-msrv

    - name: Info
      run: |
        rustup --version
        cargo --version
        cargo clippy --version

    - name: MSRV
      run: |
        cargo msrv verify
